context:
  version: "0.5.4"

package:
  name: helm-ls
  version: ${{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v${{ version }}.tar.gz
  sha256: a8a5490084839af3506c85efcf603fbd71bb9ee37222bbd7817da1da3f054ab3

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - helm-ls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  homepage: https://github.com/mrjosh/helm-ls
  repository: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
