context:
  version: "0.5.2"

package:
  name: helm-ls
  version: ${{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v${{ version }}.tar.gz
  sha256: c3884704cbe556b7092929111a9791e290afe75fc3f6ecee7ff21f7794f85101

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - helm-ls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  homepage: https://github.com/mrjosh/helm-ls
  repository: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
