context:
  version: "0.5.3"

package:
  name: helm-ls
  version: ${{ version }}

source:
  url: https://github.com/mrjosh/helm-ls/archive/v${{ version }}.tar.gz
  sha256: f3b537f579f29fa27fd2ad3bcf4746d062301151e5c599506551bfbbb0f030bb

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - helm-ls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Helm
  homepage: https://github.com/mrjosh/helm-ls
  repository: https://github.com/mrjosh/helm-ls

extra:
  recipe-maintainers:
    - danielnachun
